FROM postgres:16.2-bookworm

# Use a different Debian mirror
RUN echo 'deb http://ftp.us.debian.org/debian/ bookworm main' > /etc/apt/sources.list

RUN apt update && apt install -y nodejs npm
RUN npm i -g npx
# Solution for npx error: npm ERR! cb.apply is not a function
RUN rm /usr/local/bin/npx && npm install -g npm@latest
WORKDIR /shooter_api
COPY ./db.sql /docker-entrypoint-initdb.d
COPY . .
RUN npm install